---
#
- hosts: all
  #
  serial: 1
  order: sorted
  become: yes
  vars:
    venv_dir: /opt/openquake
    venv_bin: "{{ venv_dir }}/bin"
    server_host: "{{hostvars['server']['ansible_default_ipv4']['address']}}"
    worker_nodes_zmq: "{{ groups['worker'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(' -1,') }} -1"
    oq_version: 6803508ee95d2ee2e86871930fd0967c4c708d99

  pre_tasks:
    - name: ping hosts
      ping:

    - name: check OS
      debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}-{{ansible_python_version}}

    - name: check server host IP
      debug: msg={{ server_host }}

    - name: check workers host_cores
      debug: msg={{ worker_nodes_zmq }}

    - name: Update apt repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required extra system packages for Debian based
      apt:
        state: present
        cache_valid_time: 3600
        pkg:
         - man
         - nfs-common
         - python3
         - python3-venv
         - openssh-client
         - openssh-server
         - git

    - name: Config and Start SSHD
      shell: |
        if [ ! -d "/var/run/sshd" ]; then
           sudo mkdir -p /var/run/sshd
        fi
        sudo systemctl start sshd

    - name: Ensure user openquake exist and generate ssh key
      user:
        name: openquake
        home: /home/openquake
        shell: /bin/bash
        state: present
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa


  tasks:

    - name: Download installation scripts only on master node
      get_url:
        url: https://raw.githubusercontent.com/gem/oq-engine/master/install.py
        dest: /tmp/install.py
        mode: '0644'
      when: "'master' in group_names"

    - name: Run install script from github repo only on master node
      shell: |
        cd /home/openquake
        git clone https://github.com/gem/oq-engine.git
        cd oq-engine
        python3.11 ./install.py server --version={{ oq_version }}
      register: oq_install
      when: "'master' in group_names"

- import_playbook: inst_nfs.yaml
  when: "'master' in group_names"

- import_playbook: inst_nfs.yaml
  when: "'worker' in group_names"

- import_playbook: oq_zmq.yaml
