name: Cluster ZMQ
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: master
        required: true
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: [ ae_cluster_ansible ]

jobs:

  build-on-openbsd:
    name: BSD-MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/openbsd6
          run: |
            export AUTOCONF_VERSION=2.69
            export AUTOMAKE_VERSION=1.16
            export CFLAGS='-I/usr/local/include -L/usr/local/lib'
            if [ ! -f /usr/local/lib/libiconv.so ] ; then
                sudo ln -s /usr/local/lib/libiconv.so.* /usr/local/lib/libiconv.so
            fi
            run sudo pkg_add automake-1.16.2
            run ./autogen.sh
            run ./configure --prefix=/usr
            run make
            run sudo make install
            run file /usr/bin/ctags
            run ctags --version
  zmq_cluster:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian12
    env:
      working-directory: ./ansible/cluster

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: modprobe on NFS and create FS
        run: |
          sudo modprobe {nfs,nfsd,rpcsec_gss_krb5}
          df -h
          sudo mkdir -p /mnt/nfs

      - name: Install test dependencies.
        run: |
          pip3 install molecule[ansible,lint]
          pip3 install molecule-plugins[docker]
          pip3 install ansible
          ansible-galaxy collection install community.docker

      - name: Run Molecule tests.
        run: molecule test --destroy=never -- -vv
        working-directory: ${{env.working-directory}}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
